# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml
fast_sync = true
db_backend = "leveldb"
api_addr = "0.0.0.0:9889"
moniker = ""
chain_id = "mainnet"
[p2p]
laddr = "tcp://0.0.0.0:56659"
seeds = "172.31.35.233:56659"
